// Package genapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package genapi

import (
	"encoding/json"
	"fmt"
	"time"

	"github.com/oapi-codegen/runtime"
)

// Defines values for AsyncExecRequestLanguage.
const (
	AsyncExecRequestLanguageJavascript AsyncExecRequestLanguage = "javascript"
	AsyncExecRequestLanguageNode       AsyncExecRequestLanguage = "node"
	AsyncExecRequestLanguagePython     AsyncExecRequestLanguage = "python"
	AsyncExecRequestLanguageTypescript AsyncExecRequestLanguage = "typescript"
)

// Valid indicates whether the value is a known member of the AsyncExecRequestLanguage enum.
func (e AsyncExecRequestLanguage) Valid() bool {
	switch e {
	case AsyncExecRequestLanguageJavascript:
		return true
	case AsyncExecRequestLanguageNode:
		return true
	case AsyncExecRequestLanguagePython:
		return true
	case AsyncExecRequestLanguageTypescript:
		return true
	default:
		return false
	}
}

// Defines values for BuildDependencyRequestLanguage.
const (
	BuildDependencyRequestLanguageJavascript BuildDependencyRequestLanguage = "javascript"
	BuildDependencyRequestLanguageNode       BuildDependencyRequestLanguage = "node"
	BuildDependencyRequestLanguagePython     BuildDependencyRequestLanguage = "python"
	BuildDependencyRequestLanguageTypescript BuildDependencyRequestLanguage = "typescript"
)

// Valid indicates whether the value is a known member of the BuildDependencyRequestLanguage enum.
func (e BuildDependencyRequestLanguage) Valid() bool {
	switch e {
	case BuildDependencyRequestLanguageJavascript:
		return true
	case BuildDependencyRequestLanguageNode:
		return true
	case BuildDependencyRequestLanguagePython:
		return true
	case BuildDependencyRequestLanguageTypescript:
		return true
	default:
		return false
	}
}

// Defines values for CreateSessionRequestStatePolicy.
const (
	CreateSessionRequestStatePolicySession CreateSessionRequestStatePolicy = "session"
)

// Valid indicates whether the value is a known member of the CreateSessionRequestStatePolicy enum.
func (e CreateSessionRequestStatePolicy) Valid() bool {
	switch e {
	case CreateSessionRequestStatePolicySession:
		return true
	default:
		return false
	}
}

// Defines values for CreateSessionRequestWorkspaceRetention.
const (
	CreateSessionRequestWorkspaceRetentionExplicitDelete CreateSessionRequestWorkspaceRetention = "explicit_delete"
	CreateSessionRequestWorkspaceRetentionTtl            CreateSessionRequestWorkspaceRetention = "ttl"
)

// Valid indicates whether the value is a known member of the CreateSessionRequestWorkspaceRetention enum.
func (e CreateSessionRequestWorkspaceRetention) Valid() bool {
	switch e {
	case CreateSessionRequestWorkspaceRetentionExplicitDelete:
		return true
	case CreateSessionRequestWorkspaceRetentionTtl:
		return true
	default:
		return false
	}
}

// Defines values for CreateWorkspaceRequestRetentionMode.
const (
	CreateWorkspaceRequestRetentionModeExplicitDelete CreateWorkspaceRequestRetentionMode = "explicit_delete"
	CreateWorkspaceRequestRetentionModeTtl            CreateWorkspaceRequestRetentionMode = "ttl"
)

// Valid indicates whether the value is a known member of the CreateWorkspaceRequestRetentionMode enum.
func (e CreateWorkspaceRequestRetentionMode) Valid() bool {
	switch e {
	case CreateWorkspaceRequestRetentionModeExplicitDelete:
		return true
	case CreateWorkspaceRequestRetentionModeTtl:
		return true
	default:
		return false
	}
}

// Defines values for DependencyBuildStatus.
const (
	DependencyBuildStatusBuilding DependencyBuildStatus = "building"
	DependencyBuildStatusFailed   DependencyBuildStatus = "failed"
	DependencyBuildStatusReady    DependencyBuildStatus = "ready"
)

// Valid indicates whether the value is a known member of the DependencyBuildStatus enum.
func (e DependencyBuildStatus) Valid() bool {
	switch e {
	case DependencyBuildStatusBuilding:
		return true
	case DependencyBuildStatusFailed:
		return true
	case DependencyBuildStatusReady:
		return true
	default:
		return false
	}
}

// Defines values for EffectiveEnvironmentSelectionMode.
const (
	EffectiveEnvironmentSelectionModeAuto    EffectiveEnvironmentSelectionMode = "auto"
	EffectiveEnvironmentSelectionModeProfile EffectiveEnvironmentSelectionMode = "profile"
)

// Valid indicates whether the value is a known member of the EffectiveEnvironmentSelectionMode enum.
func (e EffectiveEnvironmentSelectionMode) Valid() bool {
	switch e {
	case EffectiveEnvironmentSelectionModeAuto:
		return true
	case EffectiveEnvironmentSelectionModeProfile:
		return true
	default:
		return false
	}
}

// Defines values for EnvironmentResolutionSelectionMode.
const (
	EnvironmentResolutionSelectionModeAuto    EnvironmentResolutionSelectionMode = "auto"
	EnvironmentResolutionSelectionModeProfile EnvironmentResolutionSelectionMode = "profile"
)

// Valid indicates whether the value is a known member of the EnvironmentResolutionSelectionMode enum.
func (e EnvironmentResolutionSelectionMode) Valid() bool {
	switch e {
	case EnvironmentResolutionSelectionModeAuto:
		return true
	case EnvironmentResolutionSelectionModeProfile:
		return true
	default:
		return false
	}
}

// Defines values for ErrorResponseErrorCode.
const (
	CONFLICT               ErrorResponseErrorCode = "CONFLICT"
	EXECCANCELLED          ErrorResponseErrorCode = "EXEC_CANCELLED"
	EXECTIMEOUT            ErrorResponseErrorCode = "EXEC_TIMEOUT"
	IDEMPOTENCYKEYCONFLICT ErrorResponseErrorCode = "IDEMPOTENCY_KEY_CONFLICT"
	INTERNALERROR          ErrorResponseErrorCode = "INTERNAL_ERROR"
	INVALIDARGUMENT        ErrorResponseErrorCode = "INVALID_ARGUMENT"
	INVALIDSELECTOR        ErrorResponseErrorCode = "INVALID_SELECTOR"
	NETWORKDENIED          ErrorResponseErrorCode = "NETWORK_DENIED"
	NOMATCHINGPROFILE      ErrorResponseErrorCode = "NO_MATCHING_PROFILE"
	PERMISSIONDENIED       ErrorResponseErrorCode = "PERMISSION_DENIED"
	POLICYDENIED           ErrorResponseErrorCode = "POLICY_DENIED"
	PRECONDITIONREQUIRED   ErrorResponseErrorCode = "PRECONDITION_REQUIRED"
	PROFILENOTAVAILABLE    ErrorResponseErrorCode = "PROFILE_NOT_AVAILABLE"
	PROFILENOTENABLED      ErrorResponseErrorCode = "PROFILE_NOT_ENABLED"
	PROFILENOTFOUND        ErrorResponseErrorCode = "PROFILE_NOT_FOUND"
	QUEUEFULL              ErrorResponseErrorCode = "QUEUE_FULL"
	QUOTAEXCEEDED          ErrorResponseErrorCode = "QUOTA_EXCEEDED"
	RESOLUTIONEXPIRED      ErrorResponseErrorCode = "RESOLUTION_EXPIRED"
	RESOLUTIONINVALID      ErrorResponseErrorCode = "RESOLUTION_INVALID"
	RUNTIMEUNAVAILABLE     ErrorResponseErrorCode = "RUNTIME_UNAVAILABLE"
	SANDBOXBUSY            ErrorResponseErrorCode = "SANDBOX_BUSY"
	SANDBOXNOTFOUND        ErrorResponseErrorCode = "SANDBOX_NOT_FOUND"
	SESSIONEXPIRED         ErrorResponseErrorCode = "SESSION_EXPIRED"
	SESSIONHASACTIVEEXECS  ErrorResponseErrorCode = "SESSION_HAS_ACTIVE_EXECS"
	SESSIONNOTFOUND        ErrorResponseErrorCode = "SESSION_NOT_FOUND"
	SESSIONSUSPENDED       ErrorResponseErrorCode = "SESSION_SUSPENDED"
	UNAUTHENTICATED        ErrorResponseErrorCode = "UNAUTHENTICATED"
	WORKSPACEQUOTAEXCEEDED ErrorResponseErrorCode = "WORKSPACE_QUOTA_EXCEEDED"
)

// Valid indicates whether the value is a known member of the ErrorResponseErrorCode enum.
func (e ErrorResponseErrorCode) Valid() bool {
	switch e {
	case CONFLICT:
		return true
	case EXECCANCELLED:
		return true
	case EXECTIMEOUT:
		return true
	case IDEMPOTENCYKEYCONFLICT:
		return true
	case INTERNALERROR:
		return true
	case INVALIDARGUMENT:
		return true
	case INVALIDSELECTOR:
		return true
	case NETWORKDENIED:
		return true
	case NOMATCHINGPROFILE:
		return true
	case PERMISSIONDENIED:
		return true
	case POLICYDENIED:
		return true
	case PRECONDITIONREQUIRED:
		return true
	case PROFILENOTAVAILABLE:
		return true
	case PROFILENOTENABLED:
		return true
	case PROFILENOTFOUND:
		return true
	case QUEUEFULL:
		return true
	case QUOTAEXCEEDED:
		return true
	case RESOLUTIONEXPIRED:
		return true
	case RESOLUTIONINVALID:
		return true
	case RUNTIMEUNAVAILABLE:
		return true
	case SANDBOXBUSY:
		return true
	case SANDBOXNOTFOUND:
		return true
	case SESSIONEXPIRED:
		return true
	case SESSIONHASACTIVEEXECS:
		return true
	case SESSIONNOTFOUND:
		return true
	case SESSIONSUSPENDED:
		return true
	case UNAUTHENTICATED:
		return true
	case WORKSPACEQUOTAEXCEEDED:
		return true
	default:
		return false
	}
}

// Defines values for ExecRecordStatus.
const (
	ExecRecordStatusCancelled ExecRecordStatus = "cancelled"
	ExecRecordStatusFailed    ExecRecordStatus = "failed"
	ExecRecordStatusQueued    ExecRecordStatus = "queued"
	ExecRecordStatusRunning   ExecRecordStatus = "running"
	ExecRecordStatusSucceeded ExecRecordStatus = "succeeded"
)

// Valid indicates whether the value is a known member of the ExecRecordStatus enum.
func (e ExecRecordStatus) Valid() bool {
	switch e {
	case ExecRecordStatusCancelled:
		return true
	case ExecRecordStatusFailed:
		return true
	case ExecRecordStatusQueued:
		return true
	case ExecRecordStatusRunning:
		return true
	case ExecRecordStatusSucceeded:
		return true
	default:
		return false
	}
}

// Defines values for ExecSessionRequestLanguage.
const (
	ExecSessionRequestLanguageJavascript ExecSessionRequestLanguage = "javascript"
	ExecSessionRequestLanguageNode       ExecSessionRequestLanguage = "node"
	ExecSessionRequestLanguagePython     ExecSessionRequestLanguage = "python"
	ExecSessionRequestLanguageTypescript ExecSessionRequestLanguage = "typescript"
)

// Valid indicates whether the value is a known member of the ExecSessionRequestLanguage enum.
func (e ExecSessionRequestLanguage) Valid() bool {
	switch e {
	case ExecSessionRequestLanguageJavascript:
		return true
	case ExecSessionRequestLanguageNode:
		return true
	case ExecSessionRequestLanguagePython:
		return true
	case ExecSessionRequestLanguageTypescript:
		return true
	default:
		return false
	}
}

// Defines values for ExecSessionResultEnvironment.
const (
	Sandbox ExecSessionResultEnvironment = "sandbox"
)

// Valid indicates whether the value is a known member of the ExecSessionResultEnvironment enum.
func (e ExecSessionResultEnvironment) Valid() bool {
	switch e {
	case Sandbox:
		return true
	default:
		return false
	}
}

// Defines values for LeaseRequestRiskLevel.
const (
	High   LeaseRequestRiskLevel = "high"
	Low    LeaseRequestRiskLevel = "low"
	Medium LeaseRequestRiskLevel = "medium"
)

// Valid indicates whether the value is a known member of the LeaseRequestRiskLevel enum.
func (e LeaseRequestRiskLevel) Valid() bool {
	switch e {
	case High:
		return true
	case Low:
		return true
	case Medium:
		return true
	default:
		return false
	}
}

// Defines values for NetworkPolicyMode.
const (
	Allowlist NetworkPolicyMode = "allowlist"
	Internal  NetworkPolicyMode = "internal"
	Internet  NetworkPolicyMode = "internet"
	None      NetworkPolicyMode = "none"
)

// Valid indicates whether the value is a known member of the NetworkPolicyMode enum.
func (e NetworkPolicyMode) Valid() bool {
	switch e {
	case Allowlist:
		return true
	case Internal:
		return true
	case Internet:
		return true
	case None:
		return true
	default:
		return false
	}
}

// Defines values for StartGUIRequestKind.
const (
	StartGUIRequestKindNovnc StartGUIRequestKind = "novnc"
)

// Valid indicates whether the value is a known member of the StartGUIRequestKind enum.
func (e StartGUIRequestKind) Valid() bool {
	switch e {
	case StartGUIRequestKindNovnc:
		return true
	default:
		return false
	}
}

// Defines values for SubmitJobRequestLanguage.
const (
	SubmitJobRequestLanguageJavascript SubmitJobRequestLanguage = "javascript"
	SubmitJobRequestLanguageNode       SubmitJobRequestLanguage = "node"
	SubmitJobRequestLanguagePython     SubmitJobRequestLanguage = "python"
	SubmitJobRequestLanguageTypescript SubmitJobRequestLanguage = "typescript"
)

// Valid indicates whether the value is a known member of the SubmitJobRequestLanguage enum.
func (e SubmitJobRequestLanguage) Valid() bool {
	switch e {
	case SubmitJobRequestLanguageJavascript:
		return true
	case SubmitJobRequestLanguageNode:
		return true
	case SubmitJobRequestLanguagePython:
		return true
	case SubmitJobRequestLanguageTypescript:
		return true
	default:
		return false
	}
}

// Defines values for ViewerDescriptorKind.
const (
	ViewerDescriptorKindNovnc ViewerDescriptorKind = "novnc"
)

// Valid indicates whether the value is a known member of the ViewerDescriptorKind enum.
func (e ViewerDescriptorKind) Valid() bool {
	switch e {
	case ViewerDescriptorKindNovnc:
		return true
	default:
		return false
	}
}

// Defines values for ViewerDescriptorStatus.
const (
	ViewerDescriptorStatusReady    ViewerDescriptorStatus = "ready"
	ViewerDescriptorStatusStarting ViewerDescriptorStatus = "starting"
	ViewerDescriptorStatusStopped  ViewerDescriptorStatus = "stopped"
)

// Valid indicates whether the value is a known member of the ViewerDescriptorStatus enum.
func (e ViewerDescriptorStatus) Valid() bool {
	switch e {
	case ViewerDescriptorStatusReady:
		return true
	case ViewerDescriptorStatusStarting:
		return true
	case ViewerDescriptorStatusStopped:
		return true
	default:
		return false
	}
}

// Defines values for WorkspaceRetentionMode.
const (
	WorkspaceRetentionModeExplicitDelete WorkspaceRetentionMode = "explicit_delete"
	WorkspaceRetentionModeTtl            WorkspaceRetentionMode = "ttl"
)

// Valid indicates whether the value is a known member of the WorkspaceRetentionMode enum.
func (e WorkspaceRetentionMode) Valid() bool {
	switch e {
	case WorkspaceRetentionModeExplicitDelete:
		return true
	case WorkspaceRetentionModeTtl:
		return true
	default:
		return false
	}
}

// Defines values for WorkspaceFileInfoEnvironment.
const (
	WorkspaceFileInfoEnvironmentWorkspace WorkspaceFileInfoEnvironment = "workspace"
)

// Valid indicates whether the value is a known member of the WorkspaceFileInfoEnvironment enum.
func (e WorkspaceFileInfoEnvironment) Valid() bool {
	switch e {
	case WorkspaceFileInfoEnvironmentWorkspace:
		return true
	default:
		return false
	}
}

// Defines values for WorkspaceFileInfoKind.
const (
	Dir  WorkspaceFileInfoKind = "dir"
	File WorkspaceFileInfoKind = "file"
)

// Valid indicates whether the value is a known member of the WorkspaceFileInfoKind enum.
func (e WorkspaceFileInfoKind) Valid() bool {
	switch e {
	case Dir:
		return true
	case File:
		return true
	default:
		return false
	}
}

// Defines values for ListJobsParamsStatus.
const (
	ListJobsParamsStatusCancelled ListJobsParamsStatus = "cancelled"
	ListJobsParamsStatusFailed    ListJobsParamsStatus = "failed"
	ListJobsParamsStatusQueued    ListJobsParamsStatus = "queued"
	ListJobsParamsStatusRunning   ListJobsParamsStatus = "running"
	ListJobsParamsStatusSucceeded ListJobsParamsStatus = "succeeded"
	ListJobsParamsStatusTimedOut  ListJobsParamsStatus = "timed_out"
)

// Valid indicates whether the value is a known member of the ListJobsParamsStatus enum.
func (e ListJobsParamsStatus) Valid() bool {
	switch e {
	case ListJobsParamsStatusCancelled:
		return true
	case ListJobsParamsStatusFailed:
		return true
	case ListJobsParamsStatusQueued:
		return true
	case ListJobsParamsStatusRunning:
		return true
	case ListJobsParamsStatusSucceeded:
		return true
	case ListJobsParamsStatusTimedOut:
		return true
	default:
		return false
	}
}

// Defines values for UploadSessionFileParamsIfNoneMatch.
const (
	Asterisk UploadSessionFileParamsIfNoneMatch = "*"
)

// Valid indicates whether the value is a known member of the UploadSessionFileParamsIfNoneMatch enum.
func (e UploadSessionFileParamsIfNoneMatch) Valid() bool {
	switch e {
	case Asterisk:
		return true
	default:
		return false
	}
}

// Artifact defines model for Artifact.
type Artifact struct {
	ArtifactId  *string    `json:"artifact_id,omitempty"`
	CreatedAt   *time.Time `json:"created_at,omitempty"`
	JobId       *string    `json:"job_id,omitempty"`
	Mime        *string    `json:"mime,omitempty"`
	Name        *string    `json:"name,omitempty"`
	Sha256      *string    `json:"sha256,omitempty"`
	Size        *int64     `json:"size,omitempty"`
	TenantId    *string    `json:"tenant_id,omitempty"`
	WorkspaceId *string    `json:"workspace_id,omitempty"`
}

// AsyncExecRequest Asynchronous exec request. Exactly one of code/command is required.
type AsyncExecRequest struct {
	// CallbackUrl Optional completion webhook. Subject to tenant allowlist, HMAC signing, and bounded retries (see §9.3).
	CallbackUrl *string   `json:"callback_url,omitempty"`
	Code        *string   `json:"code,omitempty"`
	Command     *[]string `json:"command,omitempty"`

	// Env Per-exec env overrides merged over session default_env.
	Env      *map[string]string        `json:"env,omitempty"`
	Language *AsyncExecRequestLanguage `json:"language,omitempty"`

	// TimeoutSeconds Exec timeout (starts counting from running, not queued). Bounded by profile limit.
	TimeoutSeconds *int `json:"timeout_seconds,omitempty"`

	// WorkingDir Per-exec working directory override. Defaults to session default_cwd.
	WorkingDir *string `json:"working_dir,omitempty"`
}

// AsyncExecRequestLanguage defines model for AsyncExecRequest.Language.
type AsyncExecRequestLanguage string

// AuditEvent defines model for AuditEvent.
type AuditEvent struct {
	Action       *string    `json:"action,omitempty"`
	CreatedAt    *time.Time `json:"created_at,omitempty"`
	EventId      *string    `json:"event_id,omitempty"`
	KeyId        *string    `json:"key_id,omitempty"`
	Message      *string    `json:"message,omitempty"`
	PrincipalId  *string    `json:"principal_id,omitempty"`
	ResourceId   *string    `json:"resource_id,omitempty"`
	ResourceType *string    `json:"resource_type,omitempty"`
	Status       *string    `json:"status,omitempty"`
	TenantId     *string    `json:"tenant_id,omitempty"`
	TraceId      *string    `json:"trace_id,omitempty"`
	UserId       *string    `json:"user_id,omitempty"`
}

// AuditEventList defines model for AuditEventList.
type AuditEventList struct {
	Items      *[]AuditEvent `json:"items,omitempty"`
	NextOffset *int          `json:"next_offset,omitempty"`
	Total      *int          `json:"total,omitempty"`
}

// BuildDependencyRequest Build dependencies for an already resolved immutable environment.
type BuildDependencyRequest struct {
	Environment  *ExactEnvironmentSelector       `json:"environment,omitempty"`
	Language     *BuildDependencyRequestLanguage `json:"language,omitempty"`
	Lockfile     *string                         `json:"lockfile,omitempty"`
	Manifest     *string                         `json:"manifest,omitempty"`
	Packages     *[]string                       `json:"packages,omitempty"`
	ResolutionId *string                         `json:"resolution_id,omitempty"`
	union        json.RawMessage
}

// BuildDependencyRequestLanguage defines model for BuildDependencyRequest.Language.
type BuildDependencyRequestLanguage string

// BuildDependencyRequest0 defines model for BuildDependencyRequest.0.
type BuildDependencyRequest0 = interface{}

// BuildDependencyRequest1 defines model for BuildDependencyRequest.1.
type BuildDependencyRequest1 = interface{}

// CatalogCard defines model for CatalogCard.
type CatalogCard struct {
	// AvoidWhen Display-only guidance; never consumed by the resolver.
	AvoidWhen    *[]string            `json:"avoid_when,omitempty"`
	Capabilities *[]string            `json:"capabilities,omitempty"`
	Description  *string              `json:"description,omitempty"`
	DisplayName  *string              `json:"display_name,omitempty"`
	Features     *CatalogCardFeatures `json:"features,omitempty"`
	Limits       *CatalogCardLimits   `json:"limits,omitempty"`
	Name         string               `json:"name"`

	// ProfileRevision Opaque immutable revision for exact Resolve after Catalog selection.
	ProfileRevision string    `json:"profile_revision"`
	Tags            *[]string `json:"tags,omitempty"`

	// UseWhen Display-only guidance; never consumed by the resolver.
	UseWhen *[]string `json:"use_when,omitempty"`
}

// CatalogCardFeatures defines model for CatalogCardFeatures.
type CatalogCardFeatures struct {
	SuspendResume *bool `json:"suspend_resume,omitempty"`
	Viewer        *bool `json:"viewer,omitempty"`
}

// CatalogCardLimits defines model for CatalogCardLimits.
type CatalogCardLimits struct {
	MaxConcurrentExecs    *int   `json:"max_concurrent_execs,omitempty"`
	MaxExecTimeoutSeconds *int   `json:"max_exec_timeout_seconds,omitempty"`
	MaxLogBytes           *int64 `json:"max_log_bytes,omitempty"`
	MaxSessionTtlSeconds  *int   `json:"max_session_ttl_seconds,omitempty"`
	WorkspaceQuotaMb      *int   `json:"workspace_quota_mb,omitempty"`
}

// CreateSessionRequest defines model for CreateSessionRequest.
type CreateSessionRequest struct {
	// Environment Unified environment selection. Field presence expresses intent: `profile` for explicit selection (fail-closed), `hints` for auto selection, both absent for the default profile. `profile` and `hints` are mutually exclusive (INVALID_SELECTOR when both present).
	Environment    *EnvironmentSelector `json:"environment,omitempty"`
	IdempotencyKey *string              `json:"idempotency_key,omitempty"`
	Metadata       *map[string]string   `json:"metadata,omitempty"`

	// ResolutionId Resolution ticket from /v1/environment:resolve. Mutually exclusive with environment.
	ResolutionId        *string                                 `json:"resolution_id,omitempty"`
	StatePolicy         *CreateSessionRequestStatePolicy        `json:"state_policy,omitempty"`
	TtlSeconds          *int                                    `json:"ttl_seconds,omitempty"`
	WorkspaceId         *string                                 `json:"workspace_id,omitempty"`
	WorkspaceRetention  *CreateSessionRequestWorkspaceRetention `json:"workspace_retention,omitempty"`
	WorkspaceTtlSeconds *int                                    `json:"workspace_ttl_seconds,omitempty"`
}

// CreateSessionRequestStatePolicy defines model for CreateSessionRequest.StatePolicy.
type CreateSessionRequestStatePolicy string

// CreateSessionRequestWorkspaceRetention defines model for CreateSessionRequest.WorkspaceRetention.
type CreateSessionRequestWorkspaceRetention string

// CreateWorkspaceRequest defines model for CreateWorkspaceRequest.
type CreateWorkspaceRequest struct {
	Metadata      *map[string]string                   `json:"metadata,omitempty"`
	QuotaMb       *int                                 `json:"quota_mb,omitempty"`
	RetentionMode *CreateWorkspaceRequestRetentionMode `json:"retention_mode,omitempty"`
	TtlSeconds    *int                                 `json:"ttl_seconds,omitempty"`
	WorkspaceId   *string                              `json:"workspace_id,omitempty"`
}

// CreateWorkspaceRequestRetentionMode defines model for CreateWorkspaceRequest.RetentionMode.
type CreateWorkspaceRequestRetentionMode string

// CredentialBinding defines model for CredentialBinding.
type CredentialBinding struct {
	// Env Example: GITHUB_TOKEN
	Env string    `json:"env"`
	Ref SecretRef `json:"ref"`
}

// DependencyBuild defines model for DependencyBuild.
type DependencyBuild struct {
	CachePath       *string               `json:"cache_path,omitempty"`
	CreatedAt       time.Time             `json:"created_at"`
	Error           *string               `json:"error,omitempty"`
	Fingerprint     string                `json:"fingerprint"`
	Language        string                `json:"language"`
	ProfileName     string                `json:"profile_name"`
	ProfileRevision string                `json:"profile_revision"`
	ReadOnly        bool                  `json:"read_only"`
	Status          DependencyBuildStatus `json:"status"`
	TenantId        *string               `json:"tenant_id,omitempty"`
	UpdatedAt       time.Time             `json:"updated_at"`
	WorkspaceId     *string               `json:"workspace_id,omitempty"`
}

// DependencyBuildStatus defines model for DependencyBuild.Status.
type DependencyBuildStatus string

// EffectiveEnvironment Answers what was selected, why, and whether it was degraded. Never exposes image/runtime/host internals.
type EffectiveEnvironment struct {
	Capabilities *[]string `json:"capabilities,omitempty"`

	// Degraded True only when the policy engine actively downgraded the request.
	Degraded    *bool   `json:"degraded,omitempty"`
	ProfileName *string `json:"profile_name,omitempty"`

	// ProfileRevision Opaque server-generated revision string.
	ProfileRevision *string                            `json:"profile_revision,omitempty"`
	SelectionMode   *EffectiveEnvironmentSelectionMode `json:"selection_mode,omitempty"`

	// SelectionReason Traceability, e.g. default fallback cause or unknown/unsatisfied capabilities.
	SelectionReason *[]string `json:"selection_reason,omitempty"`
}

// EffectiveEnvironmentSelectionMode defines model for EffectiveEnvironment.SelectionMode.
type EffectiveEnvironmentSelectionMode string

// EnvHints defines model for EnvHints.
type EnvHints struct {
	// Capabilities Namespaced capability tags (runtime.*, tool.*, document.*, browser.*).
	Capabilities *[]string `json:"capabilities,omitempty"`

	// Description Audit-only free text; never consumed by the resolver.
	Description *string `json:"description,omitempty"`

	// Strict When true, zero matches return NO_MATCHING_PROFILE instead of falling back to the default profile.
	Strict *bool `json:"strict,omitempty"`
}

// EnvironmentCatalog defines model for EnvironmentCatalog.
type EnvironmentCatalog struct {
	// CapabilityVocabulary Full namespaced capability vocabulary recognized by the auto resolver.
	CapabilityVocabulary *[]string      `json:"capability_vocabulary,omitempty"`
	DefaultProfile       *string        `json:"default_profile,omitempty"`
	Items                *[]CatalogCard `json:"items,omitempty"`
	NextOffset           *int           `json:"next_offset,omitempty"`
	Total                *int           `json:"total,omitempty"`
}

// EnvironmentResolution defines model for EnvironmentResolution.
type EnvironmentResolution struct {
	Capabilities    *[]string                           `json:"capabilities,omitempty"`
	ExpiresAt       *time.Time                          `json:"expires_at,omitempty"`
	ProfileName     *string                             `json:"profile_name,omitempty"`
	ProfileRevision *string                             `json:"profile_revision,omitempty"`
	ResolutionId    *string                             `json:"resolution_id,omitempty"`
	SelectionMode   *EnvironmentResolutionSelectionMode `json:"selection_mode,omitempty"`
	SelectionReason *[]string                           `json:"selection_reason,omitempty"`
}

// EnvironmentResolutionSelectionMode defines model for EnvironmentResolution.SelectionMode.
type EnvironmentResolutionSelectionMode string

// EnvironmentSelector Unified environment selection. Field presence expresses intent: `profile` for explicit selection (fail-closed), `hints` for auto selection, both absent for the default profile. `profile` and `hints` are mutually exclusive (INVALID_SELECTOR when both present).
type EnvironmentSelector struct {
	Hints   *EnvHints         `json:"hints,omitempty"`
	Profile *ProfileReference `json:"profile,omitempty"`
}

// ErrorResponse Unified error body (RFC 9457 spirit). request_id correlates with server TraceID and is always present. 429 responses also carry a Retry-After header.
type ErrorResponse struct {
	// Details Machine-readable context. Always includes retryable and may include field, resource_type, retry_after_seconds, or unmet capabilities.
	Details   ErrorResponse_Details  `json:"details"`
	ErrorCode ErrorResponseErrorCode `json:"error_code"`
	Message   string                 `json:"message"`
	RequestId string                 `json:"request_id"`
}

// ErrorResponse_Details Machine-readable context. Always includes retryable and may include field, resource_type, retry_after_seconds, or unmet capabilities.
type ErrorResponse_Details struct {
	Field                *string                `json:"field,omitempty"`
	ResourceType         *string                `json:"resource_type,omitempty"`
	RetryAfterSeconds    *int                   `json:"retry_after_seconds,omitempty"`
	Retryable            bool                   `json:"retryable"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// ErrorResponseErrorCode defines model for ErrorResponse.ErrorCode.
type ErrorResponseErrorCode string

// ExactEnvironmentSelector defines model for ExactEnvironmentSelector.
type ExactEnvironmentSelector struct {
	Profile struct {
		Name     string `json:"name"`
		Revision string `json:"revision"`
	} `json:"profile"`
}

// ExecRecord Unified exec record. Shape aligns with JobResult for client parsing consistency (§7.5). For sync exec, stdout/stderr are inline. For async exec, use the logs SSE endpoint.
type ExecRecord struct {
	CreatedAt  *time.Time `json:"created_at,omitempty"`
	DurationMs *int64     `json:"duration_ms,omitempty"`

	// EffectiveEnvironment Answers what was selected, why, and whether it was degraded. Never exposes image/runtime/host internals.
	EffectiveEnvironment *EffectiveEnvironment `json:"effective_environment,omitempty"`

	// ErrorCode Machine-readable error code (EXEC_CANCELLED, EXEC_TIMEOUT, SERVICE_RESTART, STREAM_INTERRUPTED).
	ErrorCode  *string    `json:"error_code,omitempty"`
	ExecId     *string    `json:"exec_id,omitempty"`
	ExitCode   *int       `json:"exit_code,omitempty"`
	FinishedAt *time.Time `json:"finished_at,omitempty"`

	// LogsUrl SSE log stream URL for async exec.
	LogsUrl   *string           `json:"logs_url,omitempty"`
	SessionId *string           `json:"session_id,omitempty"`
	StartedAt *time.Time        `json:"started_at,omitempty"`
	Status    *ExecRecordStatus `json:"status,omitempty"`

	// Stderr Populated only for sync exec.
	Stderr          *string `json:"stderr,omitempty"`
	StderrTruncated *bool   `json:"stderr_truncated,omitempty"`

	// Stdout Populated only for sync exec.
	Stdout          *string `json:"stdout,omitempty"`
	StdoutTruncated *bool   `json:"stdout_truncated,omitempty"`
	WorkingDir      *string `json:"working_dir,omitempty"`
}

// ExecRecordStatus defines model for ExecRecord.Status.
type ExecRecordStatus string

// ExecRecordList defines model for ExecRecordList.
type ExecRecordList struct {
	Items      *[]ExecRecord `json:"items,omitempty"`
	NextCursor *string       `json:"next_cursor,omitempty"`
	Total      *int          `json:"total,omitempty"`
}

// ExecSessionRequest Synchronous exec request. Exactly one of code/command is required.
type ExecSessionRequest struct {
	Code    *string   `json:"code,omitempty"`
	Command *[]string `json:"command,omitempty"`

	// Env Per-exec env overrides merged over session default_env.
	Env      *map[string]string          `json:"env,omitempty"`
	Language *ExecSessionRequestLanguage `json:"language,omitempty"`

	// TimeoutSeconds Exec timeout. Bounded by profile limit.
	TimeoutSeconds *int `json:"timeout_seconds,omitempty"`

	// WorkingDir Per-exec working directory override. Defaults to session default_cwd.
	WorkingDir *string `json:"working_dir,omitempty"`
}

// ExecSessionRequestLanguage defines model for ExecSessionRequest.Language.
type ExecSessionRequestLanguage string

// ExecSessionResult Synchronous Session execution result. Output fields are bounded by profile max_log_bytes.
type ExecSessionResult struct {
	// Cwd Example: /workspace
	Cwd             *string                       `json:"cwd,omitempty"`
	Environment     *ExecSessionResultEnvironment `json:"environment,omitempty"`
	ExitCode        *int                          `json:"exit_code,omitempty"`
	SandboxId       *string                       `json:"sandbox_id,omitempty"`
	SessionId       *string                       `json:"session_id,omitempty"`
	Stderr          *string                       `json:"stderr,omitempty"`
	StderrTruncated *bool                         `json:"stderr_truncated,omitempty"`
	Stdout          *string                       `json:"stdout,omitempty"`
	StdoutTruncated *bool                         `json:"stdout_truncated,omitempty"`
	WorkspaceId     *string                       `json:"workspace_id,omitempty"`
}

// ExecSessionResultEnvironment defines model for ExecSessionResult.Environment.
type ExecSessionResultEnvironment string

// ExecdCapabilities defines model for ExecdCapabilities.
type ExecdCapabilities struct {
	Command *bool `json:"command,omitempty"`
	Files   *bool `json:"files,omitempty"`
	Metrics *bool `json:"metrics,omitempty"`
	Session *bool `json:"session,omitempty"`
}

// FilesystemPolicy defines model for FilesystemPolicy.
type FilesystemPolicy struct {
	AllowedHostPaths *[]string `json:"allowed_host_paths,omitempty"`
	ReadOnlyRootfs   *bool     `json:"read_only_rootfs,omitempty"`
}

// JobList defines model for JobList.
type JobList struct {
	Items      *[]JobResult `json:"items,omitempty"`
	NextOffset *int         `json:"next_offset,omitempty"`
	Total      *int         `json:"total,omitempty"`
}

// JobResult defines model for JobResult.
type JobResult struct {
	DurationMs *int64 `json:"duration_ms,omitempty"`

	// EffectiveEnvironment Answers what was selected, why, and whether it was degraded. Never exposes image/runtime/host internals.
	EffectiveEnvironment *EffectiveEnvironment `json:"effective_environment,omitempty"`
	Error                *string               `json:"error,omitempty"`
	ErrorCode            *string               `json:"error_code,omitempty"`
	ExitCode             *int                  `json:"exit_code,omitempty"`
	FinishedAt           *time.Time            `json:"finished_at,omitempty"`
	JobId                *string               `json:"job_id,omitempty"`

	// LogsUrl SSE log stream URL; returned when ?wait expires while the job is still running.
	LogsUrl         *string     `json:"logs_url,omitempty"`
	Operation       *string     `json:"operation,omitempty"`
	OutputArtifacts *[]Artifact `json:"output_artifacts,omitempty"`
	SandboxId       *string     `json:"sandbox_id,omitempty"`
	StartedAt       *time.Time  `json:"started_at,omitempty"`
	Status          *string     `json:"status,omitempty"`
	Stderr          *string     `json:"stderr,omitempty"`
	StderrTruncated *bool       `json:"stderr_truncated,omitempty"`
	Stdout          *string     `json:"stdout,omitempty"`
	StdoutTruncated *bool       `json:"stdout_truncated,omitempty"`
	TaskType        *string     `json:"task_type,omitempty"`
	TenantId        *string     `json:"tenant_id,omitempty"`
	WorkspaceId     *string     `json:"workspace_id,omitempty"`
}

// LeaseRequest Advanced API. The authenticated tenant and user are derived exclusively from the Bearer API key and cannot be supplied by the request body. Environment selection uses the same EnvironmentSelector as Public endpoints.
type LeaseRequest struct {
	// Environment Unified environment selection. Field presence expresses intent: `profile` for explicit selection (fail-closed), `hints` for auto selection, both absent for the default profile. `profile` and `hints` are mutually exclusive (INVALID_SELECTOR when both present).
	Environment   *EnvironmentSelector `json:"environment,omitempty"`
	Metadata      *map[string]string   `json:"metadata,omitempty"`
	PolicyRequest *PolicyRequest       `json:"policy_request,omitempty"`

	// ResolutionId Mutually exclusive with environment.
	ResolutionId *string                `json:"resolution_id,omitempty"`
	RiskLevel    *LeaseRequestRiskLevel `json:"risk_level,omitempty"`
	Spec         *SandboxSpec           `json:"spec,omitempty"`
	WorkspaceId  *string                `json:"workspace_id,omitempty"`
}

// LeaseRequestRiskLevel defines model for LeaseRequest.RiskLevel.
type LeaseRequestRiskLevel string

// NetworkPolicy defines model for NetworkPolicy.
type NetworkPolicy struct {
	AllowedHosts *[]string          `json:"allowed_hosts,omitempty"`
	Mode         *NetworkPolicyMode `json:"mode,omitempty"`
}

// NetworkPolicyMode defines model for NetworkPolicy.Mode.
type NetworkPolicyMode string

// PlatformSpec defines model for PlatformSpec.
type PlatformSpec struct {
	// Architecture Example: amd64
	Architecture *string `json:"architecture,omitempty"`

	// Os Example: linux
	Os *string `json:"os,omitempty"`

	// Variant Example: v8
	Variant *string `json:"variant,omitempty"`
}

// PolicyRequest defines model for PolicyRequest.
type PolicyRequest struct {
	AllowRuntimeInstall *bool                `json:"allow_runtime_install,omitempty"`
	CredentialBindings  *[]CredentialBinding `json:"credential_bindings,omitempty"`
	Env                 *map[string]string   `json:"env,omitempty"`
	ExecTimeoutSeconds  *int                 `json:"exec_timeout_seconds,omitempty"`
	FilesystemPolicy    *FilesystemPolicy    `json:"filesystem_policy,omitempty"`
	Labels              *map[string]string   `json:"labels,omitempty"`
	NetworkPolicy       *NetworkPolicy       `json:"network_policy,omitempty"`
	Platform            *PlatformSpec        `json:"platform,omitempty"`
	ResourceLimits      *ResourceLimits      `json:"resource_limits,omitempty"`
	RuntimeProfile      *string              `json:"runtime_profile,omitempty"`
}

// ProfileReference defines model for ProfileReference.
type ProfileReference struct {
	// Name Example: office-basic
	Name string `json:"name"`

	// Revision Optional pinned revision; defaults to latest.
	Revision *string `json:"revision,omitempty"`
}

// QueueCapabilities defines model for QueueCapabilities.
type QueueCapabilities struct {
	DefaultWaitSeconds *int `json:"default_wait_seconds,omitempty"`
	MaxWaitSeconds     *int `json:"max_wait_seconds,omitempty"`
	MaxWaiting         *int `json:"max_waiting,omitempty"`
}

// QueueSnapshot defines model for QueueSnapshot.
type QueueSnapshot struct {
	Active  *int    `json:"active,omitempty"`
	PoolKey *string `json:"pool_key,omitempty"`
	Queued  *int    `json:"queued,omitempty"`
}

// RenewRequest defines model for RenewRequest.
type RenewRequest struct {
	ExtendSeconds int `json:"extend_seconds"`
}

// ResolveEnvironmentRequest defines model for ResolveEnvironmentRequest.
type ResolveEnvironmentRequest struct {
	// Environment Unified environment selection. Field presence expresses intent: `profile` for explicit selection (fail-closed), `hints` for auto selection, both absent for the default profile. `profile` and `hints` are mutually exclusive (INVALID_SELECTOR when both present).
	Environment EnvironmentSelector `json:"environment"`

	// TtlSeconds Requested ticket TTL; bounded by server config (default 30 minutes).
	TtlSeconds *int `json:"ttl_seconds,omitempty"`
}

// ResourceLimits defines model for ResourceLimits.
type ResourceLimits struct {
	Cpus     *float64 `json:"cpus,omitempty"`
	DiskMb   *int     `json:"disk_mb,omitempty"`
	MemoryMb *int     `json:"memory_mb,omitempty"`
	Pids     *int     `json:"pids,omitempty"`
}

// RuntimeCapabilities defines model for RuntimeCapabilities.
type RuntimeCapabilities struct {
	Available              *bool              `json:"available,omitempty"`
	AvailableRuntimes      *[]string          `json:"available_runtimes,omitempty"`
	DefaultRuntime         *string            `json:"default_runtime,omitempty"`
	Execd                  *ExecdCapabilities `json:"execd,omitempty"`
	Queue                  *QueueCapabilities `json:"queue,omitempty"`
	QueueSnapshots         *[]QueueSnapshot   `json:"queue_snapshots,omitempty"`
	RuntimeKind            *string            `json:"runtime_kind,omitempty"`
	RuntimeProfiles        *[]RuntimeProfile  `json:"runtime_profiles,omitempty"`
	SupportedLanguages     *[]string          `json:"supported_languages,omitempty"`
	SupportedStatePolicies *[]string          `json:"supported_state_policies,omitempty"`
	SupportedTaskTypes     *[]string          `json:"supported_task_types,omitempty"`
}

// RuntimeProfile defines model for RuntimeProfile.
type RuntimeProfile struct {
	Image      *string       `json:"image,omitempty"`
	Languages  *[]string     `json:"languages,omitempty"`
	Name       *string       `json:"name,omitempty"`
	Operations *[]string     `json:"operations,omitempty"`
	Platform   *PlatformSpec `json:"platform,omitempty"`
	Reusable   *bool         `json:"reusable,omitempty"`
	Runtime    *string       `json:"runtime,omitempty"`
	TaskTypes  *[]string     `json:"task_types,omitempty"`
	Viewer     *ViewerPolicy `json:"viewer,omitempty"`
}

// SandboxLease defines model for SandboxLease.
type SandboxLease struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// EffectiveEnvironment Answers what was selected, why, and whether it was degraded. Never exposes image/runtime/host internals.
	EffectiveEnvironment *EffectiveEnvironment   `json:"effective_environment,omitempty"`
	EffectivePolicy      *map[string]interface{} `json:"effective_policy,omitempty"`
	ExpiresAt            *time.Time              `json:"expires_at,omitempty"`
	LeaseId              *string                 `json:"lease_id,omitempty"`
	Metadata             *map[string]string      `json:"metadata,omitempty"`

	// ProfileRevision Opaque immutable Profile revision pinned when the Session is created.
	ProfileRevision *string `json:"profile_revision,omitempty"`
	ResourceVersion *int64  `json:"resource_version,omitempty"`
	RuntimeProfile  *string `json:"runtime_profile,omitempty"`
	SandboxId       *string `json:"sandbox_id,omitempty"`
	Status          *string `json:"status,omitempty"`
	TenantId        *string `json:"tenant_id,omitempty"`
	WorkspaceId     *string `json:"workspace_id,omitempty"`
}

// SandboxSpec defines model for SandboxSpec.
type SandboxSpec struct {
	Env              *map[string]string `json:"env,omitempty"`
	FilesystemPolicy *FilesystemPolicy  `json:"filesystem_policy,omitempty"`
	Image            *string            `json:"image,omitempty"`
	Labels           *map[string]string `json:"labels,omitempty"`
	NetworkPolicy    *NetworkPolicy     `json:"network_policy,omitempty"`
	Platform         *PlatformSpec      `json:"platform,omitempty"`
	ResourceLimits   *ResourceLimits    `json:"resource_limits,omitempty"`
	Runtime          *string            `json:"runtime,omitempty"`
	RuntimeProfile   *string            `json:"runtime_profile,omitempty"`
	WorkingDir       *string            `json:"working_dir,omitempty"`
}

// SecretRef defines model for SecretRef.
type SecretRef struct {
	Key  string `json:"key"`
	Name string `json:"name"`
}

// Session defines model for Session.
type Session struct {
	ActiveSandboxId *string    `json:"active_sandbox_id,omitempty"`
	CreatedAt       *time.Time `json:"created_at,omitempty"`

	// EffectiveEnvironment Answers what was selected, why, and whether it was degraded. Never exposes image/runtime/host internals.
	EffectiveEnvironment *EffectiveEnvironment `json:"effective_environment,omitempty"`
	ExpiresAt            *time.Time            `json:"expires_at,omitempty"`
	Metadata             *map[string]string    `json:"metadata,omitempty"`
	ProfileRevision      *string               `json:"profile_revision,omitempty"`
	ResourceVersion      *int64                `json:"resource_version,omitempty"`
	RuntimeProfile       *string               `json:"runtime_profile,omitempty"`
	SessionId            *string               `json:"session_id,omitempty"`
	StatePolicy          *string               `json:"state_policy,omitempty"`
	Status               *string               `json:"status,omitempty"`
	TenantId             *string               `json:"tenant_id,omitempty"`
	UserId               *string               `json:"user_id,omitempty"`
	WorkspaceId          *string               `json:"workspace_id,omitempty"`
}

// SessionContext Session execution context. cwd must be under /workspace.
type SessionContext struct {
	// Cwd Example: /workspace
	Cwd *string            `json:"cwd,omitempty"`
	Env *map[string]string `json:"env,omitempty"`
}

// StartGUIRequest defines model for StartGUIRequest.
type StartGUIRequest struct {
	Kind     *StartGUIRequestKind `json:"kind,omitempty"`
	Metadata *map[string]string   `json:"metadata,omitempty"`

	// Resolution Example: 1280x800
	Resolution *string `json:"resolution,omitempty"`
	TtlSeconds *int    `json:"ttl_seconds,omitempty"`
}

// StartGUIRequestKind defines model for StartGUIRequest.Kind.
type StartGUIRequestKind string

// SubmitJobRequest Clean public job request. Exactly one of code/command is required. `environment` and `resolution_id` are mutually exclusive. Internal fields (image, runtime, host paths) and caller-supplied identity fields (tenant_id, user_id) are not accepted on the Public surface. Tenant and user are derived exclusively from the Bearer API key.
type SubmitJobRequest struct {
	// CallbackUrl Optional completion webhook; subject to tenant allowlist, HMAC signing and bounded retries.
	CallbackUrl *string   `json:"callback_url,omitempty"`
	Code        *string   `json:"code,omitempty"`
	Command     *[]string `json:"command,omitempty"`

	// Env Merged over profile env baseline; server may redact or reject sensitive keys.
	Env *map[string]string `json:"env,omitempty"`

	// Environment Unified environment selection. Field presence expresses intent: `profile` for explicit selection (fail-closed), `hints` for auto selection, both absent for the default profile. `profile` and `hints` are mutually exclusive (INVALID_SELECTOR when both present).
	Environment      *EnvironmentSelector      `json:"environment,omitempty"`
	IdempotencyKey   *string                   `json:"idempotency_key,omitempty"`
	InputArtifactIds *[]string                 `json:"input_artifact_ids,omitempty"`
	Language         *SubmitJobRequestLanguage `json:"language,omitempty"`

	// Metadata Opaque metadata for audit. Convention: metadata["client.trace_ref"] carries the caller trace reference.
	Metadata *map[string]string `json:"metadata,omitempty"`

	// QueueWaitTimeoutSeconds Admission queue wait; unrelated to ?wait which bounds waiting for the result.
	QueueWaitTimeoutSeconds *int `json:"queue_wait_timeout_seconds,omitempty"`

	// ResolutionId Mutually exclusive with environment.
	ResolutionId *string `json:"resolution_id,omitempty"`
	SessionId    *string `json:"session_id,omitempty"`

	// TimeoutSeconds Bounded by the profile limit max_exec_timeout_seconds (discoverable via Catalog).
	TimeoutSeconds *int    `json:"timeout_seconds,omitempty"`
	WorkspaceId    *string `json:"workspace_id,omitempty"`
}

// SubmitJobRequestLanguage defines model for SubmitJobRequest.Language.
type SubmitJobRequestLanguage string

// ViewerDescriptor defines model for ViewerDescriptor.
type ViewerDescriptor struct {
	AccessToken    *string                 `json:"access_token,omitempty"`
	ExpiresAt      *time.Time              `json:"expires_at,omitempty"`
	Kind           *ViewerDescriptorKind   `json:"kind,omitempty"`
	PageUrl        *string                 `json:"page_url,omitempty"`
	ProxyUrl       *string                 `json:"proxy_url,omitempty"`
	Ready          *bool                   `json:"ready,omitempty"`
	RenewOnAccess  *bool                   `json:"renew_on_access,omitempty"`
	RuntimeProfile *string                 `json:"runtime_profile,omitempty"`
	SandboxId      *string                 `json:"sandbox_id,omitempty"`
	Status         *ViewerDescriptorStatus `json:"status,omitempty"`

	// TokenHeader Example: X-Genesis-Viewer-Token
	TokenHeader  *string `json:"token_header,omitempty"`
	WebsocketUrl *string `json:"websocket_url,omitempty"`
}

// ViewerDescriptorKind defines model for ViewerDescriptor.Kind.
type ViewerDescriptorKind string

// ViewerDescriptorStatus defines model for ViewerDescriptor.Status.
type ViewerDescriptorStatus string

// ViewerPolicy defines model for ViewerPolicy.
type ViewerPolicy struct {
	AllowedKinds    *[]string `json:"allowed_kinds,omitempty"`
	Artifacts       *[]string `json:"artifacts,omitempty"`
	DefaultKind     *string   `json:"default_kind,omitempty"`
	Port            *int      `json:"port,omitempty"`
	RenewOnAccess   *bool     `json:"renew_on_access,omitempty"`
	Supported       *bool     `json:"supported,omitempty"`
	TokenTtlSeconds *int      `json:"token_ttl_seconds,omitempty"`
}

// Workspace defines model for Workspace.
type Workspace struct {
	CreatedAt     *time.Time              `json:"created_at,omitempty"`
	ExpiresAt     *time.Time              `json:"expires_at,omitempty"`
	Metadata      *map[string]string      `json:"metadata,omitempty"`
	QuotaMb       *int                    `json:"quota_mb,omitempty"`
	RetentionMode *WorkspaceRetentionMode `json:"retention_mode,omitempty"`
	TenantId      *string                 `json:"tenant_id,omitempty"`
	UserId        *string                 `json:"user_id,omitempty"`
	WorkspaceId   *string                 `json:"workspace_id,omitempty"`
}

// WorkspaceRetentionMode defines model for Workspace.RetentionMode.
type WorkspaceRetentionMode string

// WorkspaceFileInfo defines model for WorkspaceFileInfo.
type WorkspaceFileInfo struct {
	Environment *WorkspaceFileInfoEnvironment `json:"environment,omitempty"`
	Kind        *WorkspaceFileInfoKind        `json:"kind,omitempty"`
	Mime        *string                       `json:"mime,omitempty"`
	ModTime     *time.Time                    `json:"mod_time,omitempty"`
	Name        *string                       `json:"name,omitempty"`
	Path        *string                       `json:"path,omitempty"`
	SandboxPath *string                       `json:"sandbox_path,omitempty"`
	Sha256      *string                       `json:"sha256,omitempty"`
	Size        *int64                        `json:"size,omitempty"`
}

// WorkspaceFileInfoEnvironment defines model for WorkspaceFileInfo.Environment.
type WorkspaceFileInfoEnvironment string

// WorkspaceFileInfoKind defines model for WorkspaceFileInfo.Kind.
type WorkspaceFileInfoKind string

// WorkspaceListResult defines model for WorkspaceListResult.
type WorkspaceListResult struct {
	Entries   *[]WorkspaceFileInfo `json:"entries,omitempty"`
	Limit     *int                 `json:"limit,omitempty"`
	Path      *string              `json:"path,omitempty"`
	Truncated *bool                `json:"truncated,omitempty"`
}

// ID defines model for ID.
type ID = string

// Error Unified error body (RFC 9457 spirit). request_id correlates with server TraceID and is always present. 429 responses also carry a Retry-After header.
type Error = ErrorResponse

// DownloadArtifactParams defines parameters for DownloadArtifact.
type DownloadArtifactParams struct {
	Offset *int    `form:"offset,omitempty" json:"offset,omitempty"`
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Range  *string `json:"Range,omitempty"`
}

// ListAuditEventsParams defines parameters for ListAuditEvents.
type ListAuditEventsParams struct {
	PrincipalId  *string `form:"principal_id,omitempty" json:"principal_id,omitempty"`
	KeyId        *string `form:"key_id,omitempty" json:"key_id,omitempty"`
	Action       *string `form:"action,omitempty" json:"action,omitempty"`
	ResourceType *string `form:"resource_type,omitempty" json:"resource_type,omitempty"`
	ResourceId   *string `form:"resource_id,omitempty" json:"resource_id,omitempty"`
	Limit        *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Offset       *int    `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetEnvironmentCatalogParams defines parameters for GetEnvironmentCatalog.
type GetEnvironmentCatalogParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`

	// Capability Comma-separated capability filter (AND semantics; a card must expose all listed capabilities).
	Capability *string `form:"capability,omitempty" json:"capability,omitempty"`

	// Tag Comma-separated tag filter (OR semantics; a card matching any listed tag is kept).
	Tag         *string `form:"tag,omitempty" json:"tag,omitempty"`
	IfNoneMatch *string `json:"If-None-Match,omitempty"`
}

// ListJobsParams defines parameters for ListJobs.
type ListJobsParams struct {
	Status *ListJobsParamsStatus `form:"status,omitempty" json:"status,omitempty"`
	Limit  *int                  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int                  `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListJobsParamsStatus defines parameters for ListJobs.
type ListJobsParamsStatus string

// SubmitJobParams defines parameters for SubmitJob.
type SubmitJobParams struct {
	// Wait Max duration to wait synchronously for completion, e.g. 30s. Bounded by server config.
	Wait *string `form:"wait,omitempty" json:"wait,omitempty"`
}

// ListJobArtifactsParams defines parameters for ListJobArtifacts.
type ListJobArtifactsParams struct {
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// UploadJobFileParams defines parameters for UploadJobFile.
type UploadJobFileParams struct {
	Name string `form:"name" json:"name"`
}

// StreamJobLogsParams defines parameters for StreamJobLogs.
type StreamJobLogsParams struct {
	Cursor *int `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// PatchV1SandboxesIdMetadataJSONBody defines parameters for PatchV1SandboxesIdMetadata.
type PatchV1SandboxesIdMetadataJSONBody map[string]*interface{}

// PatchV1SandboxesIdMetadataParams defines parameters for PatchV1SandboxesIdMetadata.
type PatchV1SandboxesIdMetadataParams struct {
	IfMatch string `json:"If-Match"`
}

// GetV1SandboxesIdViewerProxyPathParams defines parameters for GetV1SandboxesIdViewerProxyPath.
type GetV1SandboxesIdViewerProxyPathParams struct {
	Token *string `form:"token,omitempty" json:"token,omitempty"`
}

// MkdirSessionDirParams defines parameters for MkdirSessionDir.
type MkdirSessionDirParams struct {
	Path string `form:"path" json:"path"`
}

// ListSessionExecsParams defines parameters for ListSessionExecs.
type ListSessionExecsParams struct {
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// StreamExecLogsParams defines parameters for StreamExecLogs.
type StreamExecLogsParams struct {
	Cursor      *int64  `form:"cursor,omitempty" json:"cursor,omitempty"`
	LastEventID *string `json:"Last-Event-ID,omitempty"`
}

// RemoveSessionFileParams defines parameters for RemoveSessionFile.
type RemoveSessionFileParams struct {
	Path      string `form:"path" json:"path"`
	Recursive *bool  `form:"recursive,omitempty" json:"recursive,omitempty"`
}

// DownloadSessionFileParams defines parameters for DownloadSessionFile.
type DownloadSessionFileParams struct {
	Path string `form:"path" json:"path"`
}

// UploadSessionFileParams defines parameters for UploadSessionFile.
type UploadSessionFileParams struct {
	Path string `form:"path" json:"path"`

	// IfMatch Replace only when the current SHA-256 ETag matches.
	IfMatch *string `json:"If-Match,omitempty"`

	// IfNoneMatch Use `*` to create only when the file does not exist.
	IfNoneMatch *UploadSessionFileParamsIfNoneMatch `json:"If-None-Match,omitempty"`
}

// UploadSessionFileParamsIfNoneMatch defines parameters for UploadSessionFile.
type UploadSessionFileParamsIfNoneMatch string

// ListSessionFilesParams defines parameters for ListSessionFiles.
type ListSessionFilesParams struct {
	Path      *string `form:"path,omitempty" json:"path,omitempty"`
	Recursive *bool   `form:"recursive,omitempty" json:"recursive,omitempty"`
	Limit     *int    `form:"limit,omitempty" json:"limit,omitempty"`
}

// StatSessionFileParams defines parameters for StatSessionFile.
type StatSessionFileParams struct {
	Path *string `form:"path,omitempty" json:"path,omitempty"`
}

// SuspendSessionParams defines parameters for SuspendSession.
type SuspendSessionParams struct {
	// Force When true, cancel all running execs before suspending.
	Force *bool `form:"force,omitempty" json:"force,omitempty"`
}

// BuildDependenciesJSONRequestBody defines body for BuildDependencies for application/json ContentType.
type BuildDependenciesJSONRequestBody = BuildDependencyRequest

// ResolveEnvironmentJSONRequestBody defines body for ResolveEnvironment for application/json ContentType.
type ResolveEnvironmentJSONRequestBody = ResolveEnvironmentRequest

// SubmitJobJSONRequestBody defines body for SubmitJob for application/json ContentType.
type SubmitJobJSONRequestBody = SubmitJobRequest

// PostV1SandboxesIdGuiStartJSONRequestBody defines body for PostV1SandboxesIdGuiStart for application/json ContentType.
type PostV1SandboxesIdGuiStartJSONRequestBody = StartGUIRequest

// PatchV1SandboxesIdMetadataJSONRequestBody defines body for PatchV1SandboxesIdMetadata for application/json ContentType.
type PatchV1SandboxesIdMetadataJSONRequestBody PatchV1SandboxesIdMetadataJSONBody

// PostV1SandboxesIdSessionsJSONRequestBody defines body for PostV1SandboxesIdSessions for application/json ContentType.
type PostV1SandboxesIdSessionsJSONRequestBody = ExecSessionRequest

// PostV1SandboxesIdRenewJSONRequestBody defines body for PostV1SandboxesIdRenew for application/json ContentType.
type PostV1SandboxesIdRenewJSONRequestBody = RenewRequest

// PostV1SandboxesLeaseJSONRequestBody defines body for PostV1SandboxesLease for application/json ContentType.
type PostV1SandboxesLeaseJSONRequestBody = LeaseRequest

// CreateSessionJSONRequestBody defines body for CreateSession for application/json ContentType.
type CreateSessionJSONRequestBody = CreateSessionRequest

// PatchSessionContextJSONRequestBody defines body for PatchSessionContext for application/json ContentType.
type PatchSessionContextJSONRequestBody = SessionContext

// ExecSessionJSONRequestBody defines body for ExecSession for application/json ContentType.
type ExecSessionJSONRequestBody = ExecSessionRequest

// ExecSessionAsyncJSONRequestBody defines body for ExecSessionAsync for application/json ContentType.
type ExecSessionAsyncJSONRequestBody = AsyncExecRequest

// RenewSessionJSONRequestBody defines body for RenewSession for application/json ContentType.
type RenewSessionJSONRequestBody = RenewRequest

// PostV1WorkspacesJSONRequestBody defines body for PostV1Workspaces for application/json ContentType.
type PostV1WorkspacesJSONRequestBody = CreateWorkspaceRequest

// Getter for additional properties for ErrorResponse_Details. Returns the specified
// element and whether it was found
func (a ErrorResponse_Details) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ErrorResponse_Details
func (a *ErrorResponse_Details) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ErrorResponse_Details to handle AdditionalProperties
func (a *ErrorResponse_Details) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["field"]; found {
		err = json.Unmarshal(raw, &a.Field)
		if err != nil {
			return fmt.Errorf("error reading 'field': %w", err)
		}
		delete(object, "field")
	}

	if raw, found := object["resource_type"]; found {
		err = json.Unmarshal(raw, &a.ResourceType)
		if err != nil {
			return fmt.Errorf("error reading 'resource_type': %w", err)
		}
		delete(object, "resource_type")
	}

	if raw, found := object["retry_after_seconds"]; found {
		err = json.Unmarshal(raw, &a.RetryAfterSeconds)
		if err != nil {
			return fmt.Errorf("error reading 'retry_after_seconds': %w", err)
		}
		delete(object, "retry_after_seconds")
	}

	if raw, found := object["retryable"]; found {
		err = json.Unmarshal(raw, &a.Retryable)
		if err != nil {
			return fmt.Errorf("error reading 'retryable': %w", err)
		}
		delete(object, "retryable")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ErrorResponse_Details to handle AdditionalProperties
func (a ErrorResponse_Details) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Field != nil {
		object["field"], err = json.Marshal(a.Field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'field': %w", err)
		}
	}

	if a.ResourceType != nil {
		object["resource_type"], err = json.Marshal(a.ResourceType)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'resource_type': %w", err)
		}
	}

	if a.RetryAfterSeconds != nil {
		object["retry_after_seconds"], err = json.Marshal(a.RetryAfterSeconds)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'retry_after_seconds': %w", err)
		}
	}

	object["retryable"], err = json.Marshal(a.Retryable)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'retryable': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// AsBuildDependencyRequest0 returns the union data inside the BuildDependencyRequest as a BuildDependencyRequest0
func (t BuildDependencyRequest) AsBuildDependencyRequest0() (BuildDependencyRequest0, error) {
	var body BuildDependencyRequest0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromBuildDependencyRequest0 overwrites any union data inside the BuildDependencyRequest as the provided BuildDependencyRequest0
func (t *BuildDependencyRequest) FromBuildDependencyRequest0(v BuildDependencyRequest0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeBuildDependencyRequest0 performs a merge with any union data inside the BuildDependencyRequest, using the provided BuildDependencyRequest0
func (t *BuildDependencyRequest) MergeBuildDependencyRequest0(v BuildDependencyRequest0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsBuildDependencyRequest1 returns the union data inside the BuildDependencyRequest as a BuildDependencyRequest1
func (t BuildDependencyRequest) AsBuildDependencyRequest1() (BuildDependencyRequest1, error) {
	var body BuildDependencyRequest1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromBuildDependencyRequest1 overwrites any union data inside the BuildDependencyRequest as the provided BuildDependencyRequest1
func (t *BuildDependencyRequest) FromBuildDependencyRequest1(v BuildDependencyRequest1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeBuildDependencyRequest1 performs a merge with any union data inside the BuildDependencyRequest, using the provided BuildDependencyRequest1
func (t *BuildDependencyRequest) MergeBuildDependencyRequest1(v BuildDependencyRequest1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t BuildDependencyRequest) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	if err != nil {
		return nil, err
	}
	object := make(map[string]json.RawMessage)
	if t.union != nil {
		err = json.Unmarshal(b, &object)
		if err != nil {
			return nil, err
		}
	}

	if t.Environment != nil {
		object["environment"], err = json.Marshal(t.Environment)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'environment': %w", err)
		}
	}

	if t.Language != nil {
		object["language"], err = json.Marshal(t.Language)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'language': %w", err)
		}
	}

	if t.Lockfile != nil {
		object["lockfile"], err = json.Marshal(t.Lockfile)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'lockfile': %w", err)
		}
	}

	if t.Manifest != nil {
		object["manifest"], err = json.Marshal(t.Manifest)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'manifest': %w", err)
		}
	}

	if t.Packages != nil {
		object["packages"], err = json.Marshal(t.Packages)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'packages': %w", err)
		}
	}

	if t.ResolutionId != nil {
		object["resolution_id"], err = json.Marshal(t.ResolutionId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'resolution_id': %w", err)
		}
	}
	b, err = json.Marshal(object)
	return b, err
}

func (t *BuildDependencyRequest) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	if err != nil {
		return err
	}
	object := make(map[string]json.RawMessage)
	err = json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["environment"]; found {
		err = json.Unmarshal(raw, &t.Environment)
		if err != nil {
			return fmt.Errorf("error reading 'environment': %w", err)
		}
	}

	if raw, found := object["language"]; found {
		err = json.Unmarshal(raw, &t.Language)
		if err != nil {
			return fmt.Errorf("error reading 'language': %w", err)
		}
	}

	if raw, found := object["lockfile"]; found {
		err = json.Unmarshal(raw, &t.Lockfile)
		if err != nil {
			return fmt.Errorf("error reading 'lockfile': %w", err)
		}
	}

	if raw, found := object["manifest"]; found {
		err = json.Unmarshal(raw, &t.Manifest)
		if err != nil {
			return fmt.Errorf("error reading 'manifest': %w", err)
		}
	}

	if raw, found := object["packages"]; found {
		err = json.Unmarshal(raw, &t.Packages)
		if err != nil {
			return fmt.Errorf("error reading 'packages': %w", err)
		}
	}

	if raw, found := object["resolution_id"]; found {
		err = json.Unmarshal(raw, &t.ResolutionId)
		if err != nil {
			return fmt.Errorf("error reading 'resolution_id': %w", err)
		}
	}

	return err
}
